# Generated by Django 2.2.16 on 2022-07-09 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст комменатрия', verbose_name='Текст комменатрия')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Автоматическое добавление времени публикации комментария', verbose_name='Дата публикации комментария')),
                ('author', models.ForeignKey(help_text='Имя автора комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('post', models.ForeignKey(blank=True, help_text='Оставьте Ваш комментарий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccomments', to='posts.Post', verbose_name='Комментарий')),
            ],
        ),
    ]
